### ISSUE TITLE
DACBerry-400 not working on kernel 5.10.60-v7l

### ISSUE THREAD

**Issue by rbnpi** [osaelectronics/DACBerry-400#1]
Just got a DACBerry-400 today from The PiHUT. On my up to date RaspberryPI OS the kernel is 5.10.60-v7l I get no sound whatsover out of the DAC. The audio check routine appears to be running but I hear nothing. Is this the correct installer to be using?
Whatt can I do to get it going.

**Comment by osaelectronics** [comment]
Hello,

We are updating the driver to work on the latest kernel, it will be ready today/tomorrow. In the meantime you may can install an older version of Pi OS and not update/upgrade it! 

Thank you!

**Comment by osaelectronics** [comment]
Updated to work with 5.10.60-v7l now! Please check!

**Comment by rbnpi** [comment]
I've downloaded and installed this, but it still does not seem to work. I've checked that the two kernel files for 5.10.60-v7l are installed correctly.

**Comment by osaelectronics** [comment]
Hello,

Some other users reported that it is working for them now, I suggest you to do a fresh install, and check if the board is correctly connected! 

Also, can you try to see if the board is detected using the "sudo i2cdetect -y 1" command? 

Keep us posted.-

**Comment by rbnpi** [comment]
Tried 2 cards and not working. I can see audio if I look at pavucontrol but hear nothing. I2cdetect shows a grid with values 03 to 77. First three entries blank. 
I think the board may be damaged.

**Comment by osaelectronics** [comment]
Robin,

So both DACBerry 400 are not working? And show the same I2C behaviour? All should be plenty of "--" execept the 18 address, what should show "UU". If you see more numbers is because there is a conflict on the I2C bus, probably casued by DACBerry if it got damaged. Can you please make sure the card is connected correctly? Is the board hot when you plug it? Probably the best solution is to ask Pi Hut to send you new board(s), so far we have no more issue reports except you and other customer, so is probably board damage related!

**Comment by rbnpi** [comment]
Sorry by 2 cards I meant two sd cards. I only have the one dac400
Looks like it is damaged from the i2c grid output.  Will contact pihut about it.

**Comment by osaelectronics** [comment]
Oh no problem! Looks like it is probably damaged. Contact Pihut and try to get another one! Please be very careful when pluging the new board to Pi 400, be sure it is properly connected prior connecting the power cable. Ensure the board is not hot, and if everything is well connected, it should work as expected!

**Comment by rbnpi** [comment]
Just got a replacement board, but not tried it yet. I notice however that sudo apt install full-upgrade is now installing
Linux raspberrypi 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux
Does this mean yet another driver for this kernel version? In the meantime I'll try it out with an earlier version.

**Comment by osaelectronics** [comment]
Hello Robin, we really don't know what those guys are doing, updating kernel every week... Please, try to give a try without doing an update first, to see everything works well! We will update the driver within this week for the 5.10.63 in any case. Please kee us posted!

**Comment by rbnpi** [comment]
Tested and working with kernel 5.10.60

**Comment by osaelectronics** [comment]
Great! So closing this issue!

**Comment by rbnpi** [comment]
But not tried it on the latest kernel yet....
