### ISSUE TITLE
no pat-get check for git

### ISSUE THREAD

**Issue by MathieuCGit** [osaelectronics/DACBerry-400#2]
Hello,

I guess your script should check if git is installed but actually it doesn't :

`    if apt_pkg_req "apt-utils" &> /dev/null; then
        apt_pkg_install "apt-utils"
    fi
    if ! command -v curl > /dev/null; then
        apt_pkg_install "curl"
    fi
    if ! command -v wget > /dev/null; then
        apt_pkg_install "wget"
    fi`

**Comment by MathieuCGit** [comment]
Sorry for the noise, I found it later in the script :-s

**Comment by osaelectronics** [comment]
No worries! :D
